language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_ed385243761a_key -iv $encrypted_ed385243761a_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d


